### ISSUE TITLE
Task 'Solr Cloud upload config' fails (Solr v. 6.6.6)

### ISSUE THREAD

**Issue by jsommr** [lean-delivery/ansible-role-solr-cloud#4]
'Solr Cloud upload config' fails with the following error:

`
failed: [10.1.1.6] (item=/var/solr/data/configsets/data_driven_schema_configs) => {"changed": false, "cmd": ["/opt/solr-6.6.6/bin/solr", "zk", "-upconfig", "-n", "/var/solr/data/configsets/data_driven_schema_configs", "-d", "/var/solr/data/configsets/data_driven_schema_configs/conf"], "delta": "0:00:00.075575", "end": "2019-05-17 15:06:35.438251", "msg": "non-zero return code", "rc": 1, "solr_conf_set": "/var/solr/data/configsets/data_driven_schema_configs", "start": "2019-05-17 15:06:35.362676", "stderr": "", "stderr_lines": [], "stdout": "\nERROR: Zookeeper address (-z) argument is required or ZK_HOST must be specified in the solr.in.sh file.\n\n  Usage: solr zk upconfig|downconfig -d <confdir> -n <configName> [-z zkHost]\n         solr zk cp [-r] <src> <dest> [-z zkHost]\n         solr zk rm [-r] <path> [-z zkHost]\n         solr zk mv <src> <dest> [-z zkHost]\n         solr zk ls [-r] <path> [-z zkHost]\n         solr zk mkroot <path> [-z zkHost]", "stdout_lines": ["", "ERROR: Zookeeper address (-z) argument is required or ZK_HOST must be specified in the solr.in.sh file.", "", "  Usage: solr zk upconfig|downconfig -d <confdir> -n <configName> [-z zkHost]", "         solr zk cp [-r] <src> <dest> [-z zkHost]", "         solr zk rm [-r] <path> [-z zkHost]", "         solr zk mv <src> <dest> [-z zkHost]", "         solr zk ls [-r] <path> [-z zkHost]", "         solr zk mkroot <path> [-z zkHost]"]}
`

# Fix
file: tasks/Linux.yml

<pre>
- name: Solr Cloud upload config
  command: >-
    {{ solr_dest_path }}/bin/solr zk -upconfig -n {{ solr_conf_set<b> | basename </b>}}
    -d '{{ solr_configset_path }}/{{ solr_conf_set | basename }}/conf'
  loop: '{{ configset_list }}'
  loop_control:
    loop_var: solr_conf_set
  run_once: True
  when:
    - zk_hosts | length
    - configset_list | length
  changed_when: False
  <b>become: True
  become_user: "{{ solr_user }}"</b>
</pre>

Set `solr_insh_default` to `/opt/solr/bin/solr.in.sh`

**Comment by tgadiev** [comment]
Fixed in latest releases.
